FROM mcr.microsoft.com/playwright:v1.61.0-noble

COPY build-tmp/pixi-build /usr/local/bin/pixi

RUN apt-get update \
    && apt-get install --yes --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && npm install --global t3@latest playwright@1.61.0 \
    && npm cache clean --force
